name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to destroy"
        required: true
        type: choice
        options: [dev, staging, prod]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.6.6

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set environment
    - name: Set environment
      id: env
      run: |
        TARGET="${{ github.event.inputs.environment }}"

        echo "Selected environment: $TARGET"

        if [[ "$TARGET" == "dev" ]]; then
          echo "dir=terraform/environments/dev" >> $GITHUB_OUTPUT
          echo "role=${{ secrets.AWS_ROLE_DEV }}" >> $GITHUB_OUTPUT
        elif [[ "$TARGET" == "staging" ]]; then
          echo "dir=terraform/environments/staging" >> $GITHUB_OUTPUT
          echo "role=${{ secrets.AWS_ROLE_STAGING }}" >> $GITHUB_OUTPUT
        elif [[ "$TARGET" == "prod" ]]; then
          echo "dir=terraform/environments/prod" >> $GITHUB_OUTPUT
          echo "role=${{ secrets.AWS_ROLE_PROD }}" >> $GITHUB_OUTPUT
        else
          echo "❌ Invalid environment"
          exit 1
        fi

    # Debug
    - name: Debug role
      run: echo "ROLE=${{ steps.env.outputs.role }}"

    # AWS OIDC login
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ steps.env.outputs.role }}
        aws-region: ${{ env.AWS_REGION }}

    # Setup Terraform
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    # Terraform Init
    - name: Terraform Init
      run: terraform init
      working-directory: ${{ steps.env.outputs.dir }}

    # Destroy Plan for safe preview
    - name: Terraform Destroy Plan
      run: terraform plan -destroy -no-color
      working-directory: ${{ steps.env.outputs.dir }}

    # Confirm Destroy
    - name: Confirm destroy
      run: |
        if [[ "${{ github.event.inputs.environment }}" == "prod" ]]; then
          echo "⚠️ Destroying PROD environment"
          sleep 10
        fi

    # Destroy
    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      working-directory: ${{ steps.env.outputs.dir }}