name: Terraform Destroy

on:
  pull_request:
    branches: [develop, staging, main]
  push:
    branches: [develop, staging, main]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to destroy (dev, staging, prod)"
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod

# permissions
permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.6.6

# Prevent parallel destroys per env
concurrency:
  group: terraform-destroy-${{ github.event.inputs.environment }}
  cancel-in-progress: false

jobs:
  destroy:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set environment
      id: env
      run: |
        case "${{ github.event.inputs.environment }}" in
          dev)
            echo "dir=terraform/environments/dev" >> $GITHUB_OUTPUT
            echo "role=${{ secrets.AWS_ROLE_DEV }}" >> $GITHUB_OUTPUT
            ;;
          staging)
            echo "dir=terraform/environments/staging" >> $GITHUB_OUTPUT
            echo "role=${{ secrets.AWS_ROLE_STAGING }}" >> $GITHUB_OUTPUT
            ;;
          prod)
            echo "dir=terraform/environments/prod" >> $GITHUB_OUTPUT
            echo "role=${{ secrets.AWS_ROLE_PROD }}" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "❌ Invalid environment"
            exit 1
            ;;
        esac

    - name: Configure AWS (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ steps.env.outputs.role }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ steps.env.outputs.dir }}

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      working-directory: ${{ steps.env.outputs.dir }}